### ISSUE TITLE
query() only executing first statement

### ISSUE THREAD

**Issue by wetbadger** [2shady4u/godot-sqlite#78] opened 2022-05-05 14:17 UTC
**Environment:**
 - OS: Linux Mint 20.3
 - Godot version: 3.4.2
 - _godot-sqlite_ version: 

**Issue description:**
My query has several statements separated by semicolons, but only the first statement runs. 
No error is returned in error_message().
Is this expected behavior?

**Steps to reproduce:**
Create a new db. 
Create a query with more than 1 statement.
Try to run the query.
Only the first statement runs.

**Minimal reproduction project:**
```
func _ready():
  db = SQLite.new()
  db.path = "res://path/to/database.db"
  db.open_db()
  db.query( """
  
	  INSERT INTO people ('name','job_id','age')
	  VALUES ('Bill Smith','2','20');
		  
	  INSERT INTO people ('name','job_id','age')
	  VALUES ('Tom Jones','3','20');
  """
  )
```

**Comment by 2shady4u** [comment] 2022-05-05 14:23
Hi @wetbadger !
This is a duplicate of https://github.com/2shady4u/godot-sqlite/issues/58 😄 

Basically only the first statement (= until the first ;) will execute ATM 🤷‍♂️

**Comment by wetbadger** [comment] 2022-05-05 22:32
> Hi @wetbadger ! This is a duplicate of #58 smile
> 
> Basically only the first statement (= until the first ";") will execute ATM man_shrugging

Oops, didn't see that one XD

Using insert_rows() seems to be an acceptable workaround in this case.

**Comment by 2shady4u** [comment] 2022-05-07 12:08
> > Hi @wetbadger ! This is a duplicate of #58 smile
> > Basically only the first statement (= until the first ";") will execute ATM man_shrugging
> 
> Oops, didn't see that one XD
> 
> Using insert_rows() seems to be an acceptable workaround in this case.

In your case this is indeed the recommended work-around for this situation :)

I'm closing this in favor of #58 which predates this issue and discusses the exact same limitation.

**Closed by 2shady4u** 2022-05-07 12:08 UTC
Labels: bug
