### ISSUE TITLE
The app can't open android dynamic library

### ISSUE THREAD

**Issue by papanouel** [2shady4u/godot-sqlite#177] opened 2024-06-07 13:17 UTC
**Environment:**
 - OS: Android 12
 - Device: Google Pixel 7, OPPO RENO 7a
 - Godot version: 4.2
 - _godot-sqlite_ version: 4.3

**Issue description:**

While the plugin is working perfectly fine on iOS and on my mac (running in editor), I get the following error on Android devices at launch of the app:

06-07 21:46:44.617 32767 32767 E godot   : USER ERROR: Can't open dynamic library: addons/godot-sqlite/bin/libgdsqlite.android.template_debug.arm64.so. Error: dlopen failed: library "libgdsqlite.android.template_debug.arm64.so" not found.
06-07 21:46:44.617 32767 32767 E godot   :    at: open_dynamic_library (platform/android/os_android.cpp:200)
06-07 21:46:44.617 32767 32767 E godot   : USER ERROR: GDExtension dynamic library not found: addons/godot-sqlite/bin/libgdsqlite.android.template_debug.arm64.so
06-07 21:46:44.617 32767 32767 E godot   :    at: open_library (core/extension/gdextension.cpp:719)
06-07 21:46:44.617 32767 32767 E godot   : USER ERROR: Failed loading resource: res://addons/godot-sqlite/gdsqlite.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
06-07 21:46:44.617 32767 32767 E godot   :    at: _load (core/io/resource_loader.cpp:275)
06-07 21:46:44.617 32767 32767 E godot   : USER ERROR: Error loading extension: res://addons/godot-sqlite/gdsqlite.gdextension

**Steps to reproduce:**
- Install the plugins in the project
- Create AAB package and install to the device OR remote launch from editor to Android device
- The app will crash showing the previously mentioned logs

**Minimal reproduction project:**
It is happening at startups. The only code is below:
var db= SQLite.new()
db.path = "user://shots.db"
var result= db.open_db()

**Additional context**
The line referencing the library is present in gdsqlite.gdextension and in resource path
android.template_release.x86_64 = "res://addons/godot-sqlite/bin/libgdsqlite.android.template_release.x86_64.so"

<img width="1076" alt="image" src="https://github.com/2shady4u/godot-sqlite/assets/414019/3f2de5e0-0eea-4a9a-bd5c-1d1f6e171fc2">

**Comment by 2shady4u** [comment] 2024-06-07 18:18
Hello @papanouel :)

Could you download the android binary from the latest Github Actions and see if the problem is also present there?
https://github.com/2shady4u/godot-sqlite/actions/runs/9140414376

Direct link:
https://github.com/2shady4u/godot-sqlite/actions/runs/9140414376/artifacts/1515868254

**Comment by papanouel** [comment] 2024-06-08 02:23
Hello :)
I just replaced previous libraries by the new onces, but unfortunately still the same error 😕

One error log I didn't see initially appears when remote launching the app from editor to the Android device (shows up in the godot output window):

`No suitable library found for GDExtension: res://addons/godot-sqlite/gdsqlite.gdextension. Possible feature flags for your platform: mobile, android, etc2, astc, arm32, arm64, template, debug, template_debug`

Also in the error log I shared with you initially it does mentioned:
USER ERROR: GDExtension dynamic library not found: addons/godot-sqlite/bin/libgdsqlite.android.template_debug.arm64.so 
without the "res://" part of the path. Not sure it is an issue but just mentioning it just in case.

As we never know, sharing the content of gdsqlite.gdextension, but I think everything looks fine. I'll keep checking however let me know if you  have some suggestions 😊

------------------------------------------------------------
[configuration]

entry_symbol = "sqlite_library_init"
compatibility_minimum = 4.2

[libraries]

macos = "res://addons/godot-sqlite/bin/libgdsqlite.macos.template_debug.framework"
macos.template_release = "res://addons/godot-sqlite/bin/libgdsqlite.macos.template_release.framework"
windows.x86_64 = "res://addons/godot-sqlite/bin/libgdsqlite.windows.template_debug.x86_64.dll"
windows.template_release.x86_64 = "res://addons/godot-sqlite/bin/libgdsqlite.windows.template_release.x86_64.dll"
linux.x86_64 = "res://addons/godot-sqlite/bin/libgdsqlite.linux.template_debug.x86_64.so"
linux.template_release.x86_64 = "res://addons/godot-sqlite/bin/libgdsqlite.linux.template_release.x86_64.so"
android.arm64 = "res://addons/godot-sqlite/bin/libgdsqlite.android.template_debug.arm64.so"
android.template_release.arm64 = "res://addons/godot-sqlite/bin/libgdsqlite.android.template_release.arm64.so"
android.x86_64 = "res://addons/godot-sqlite/bin/libgdsqlite.android.template_debug.x86_64.so"
android.template_release.x86_64 = "res://addons/godot-sqlite/bin/libgdsqlite.android.template_release.x86_64.so"
ios.arm64 = "res://addons/godot-sqlite/bin/libgdsqlite.ios.template_debug.arm64.dylib"
ios.template_release.arm64 = "res://addons/godot-sqlite/bin/libgdsqlite.ios.template_release.arm64.dylib"
web.wasm32 = "res://addons/godot-sqlite/bin/libgdsqlite.web.template_debug.wasm32.wasm"
web.template_release.wasm32 = "res://addons/godot-sqlite/bin/libgdsqlite.web.template_release.wasm32.wasm"

[dependencies]

macos = {}
macos.template_release = {}
windows.x86_64 = {}
windows.template_release.x86_64 = {}
linux.x86_64 = {}
linux.template_release.x86_64 = {}
android.arm64 = {}
android.template_release.arm64 = {}
android.x86_64 = {}
android.template_release.x86_64 = {}
ios.arm64 = {}
ios.template_release.arm64 = {}
web.wasm32 = {}
web.template_release.wasm32 = {}
------------------------------------------------------------

**Comment by papanouel** [comment] 2024-06-08 08:07
FYI: I made it work by simply copy paste the libraries in the exported android build folders.
So the issue is the not the android libraries themselves, but the fact that during android export, Godot doesn't seem to be able to find the libraries in the addons/godot-sqlite folder 🤷 🤔
![image](https://github.com/2shady4u/godot-sqlite/assets/414019/290836fd-c0a6-4130-9b2a-193df223d251)

**Comment by 2shady4u** [comment] 2024-06-08 08:20
> FYI: I made it work by simply copy paste the libraries in the exported android build folders. So the issue is not the android libraries themselves, but the fact that during android export, Godot doesn't seem to be able to find the libraries in the addons/godot-sqlite folder 🤷 🤔 ![image](https://private-user-images.githubusercontent.com/414019/337860633-290836fd-c0a6-4130-9b2a-193df223d251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MzQ5OTQsIm5iZiI6MTcxNzgzNDY5NCwicGF0aCI6Ii80MTQwMTkvMzM3ODYwNjMzLTI5MDgzNmZkLWMwYTYtNDEzMC05YjJhLTE5M2RmMjIzZDI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwODE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGI2Y2Y3NmU2ZjRmNzJmNDljODU5MDkwMzUwNzNlMGQ0Mjk4MTk1YWQ3ODExZTY4ZTM5MGVlNzJmMjk5Y2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gS21tLb_GQ3oYFLYbzA60EHmZL1fbMtSKRBbHXi7hnM)

That is interesting 🤔 
I'll try to see if I get the same issue with my Android phone.
Regardless of the results, I'll have to check if the issue is due to this repository or if there's an upstream issue in godot-cpp instead.

**Comment by papanouel** [comment] 2024-06-08 09:35
Got it 👍 Thx

Quick last question and then I will leave you alone 😊 
I also need arm32 version of android libraries. I saw that they were not included and thought about cloning the repository and generating the build for arch arm32 myself following the guideline you wrote. 
Before doing that just wanted to confirm with you if there was no specific hurdle in front of me, or eventually if you had the arm32 build already somewhere 😜

Let me know!

PS: BTW I love this plugin. Super useful!

**Comment by papanouel** [comment] 2024-06-08 09:58
Nevermind. just did it, and it was super simple! Have a great weekend!!

**Comment by 2shady4u** [comment] 2024-06-08 14:31
I am having the same issue on my Asus ZenFone 8:

```
ERROR: No suitable library found for GDExtension: res://addons/godot-sqlite/gdsqlite.gdextension. Possible feature flags for your platform: mobile, android, etc2, astc, arm32, arm64, template, debug, template_debug
   at: (./editor/plugins/gdextension_export_plugin.h:129)
```

I assume it is an upstream issue with godot-cpp.
I'll investigate a bit more...

**Comment by 2shady4u** [comment] 2024-06-08 14:57
@papanouel Okay, it seems that it is caused by the Android export settings :)

In the demo project I set both the armeabi-v7a and arm64-v8a architectures as being enabled:
```
architectures/armeabi-v7a=true
architectures/arm64-v8a=true
```

This results in an error because the armeabi-v7a binary is not included in the binaries of the demo project.
When I disable the armeabi-v7a architecture (and thus only leave the arm64-v8a arch enabled), everything works without any issue 😄 

I have pushed a fix (= disabling the armeabi-v7a architecture in the export settings) and will close this issue as a result.

**Closed by 2shady4u** 2024-06-08 14:57 UTC
Labels: bug

**Comment by shiva30122** [comment] 2024-07-05 19:58
Error  : No suitable library found for GDExtension: res://addons/godot-sqlite/gdsqlite.gdextension. Possible feature flags for your platform: mobile, android, etc2, astc, arm32, arm64, template, debug, template_debug, single

the res://addons/godot-sqlite/gdsqlite.gdextension dose not have compile architecture.os !. 
          LOCATION :
         "res://addons/godot-sqlite/bin/"    
           PATH :  libgdsqlite.android.template_[debug.arm64.so](javascript:void(0);)
   It ONLY SUPPORTS amrabi-a8v architecture into APK ,
   If i use "armeabi-v7a", "x86", "x86_64" then the APK CRASH even I use GRADLE into APK OR ABB 

ANY SOLUTION !..................
HOW TO FIX ?.......................
OR any binaries avaliabe ?...........
