### ISSUE TITLE
Can't save blobs with db.update_rows(...)

### ISSUE THREAD

**Issue by mrimvo** [2shady4u/godot-sqlite#41] opened 2021-03-16 16:22 UTC
Using db.update_rows(...), saving **blobs** does not work.

Output is:
```
UPDATE users SET myblob=[PoolByteArray] WHERE uid = 4026253021;
SQL error: no such column: PoolByteArray
```

But I think it should be something like:
```
UPDATE users SET myblob=x'789c....' WHERE uid = 4026253021;
```

I *can* save blobs with db.insert_row(...) though. But updating blobs doesn't work.

----
As a side note, I also tried
```
db.query_with_bindings(
    "UPDATE users SET ?=? WHERE uid = ?;",
    ["myblob", PoolByteArray([1,2]), uid])
```
But in the log it says:

```
UPDATE users SET ?=? WHERE uid = ?;
SQL error: near "?": syntax error
```
So there seems to be another issue with `query_with_bindings`

**Comment by 2shady4u** [comment] 2021-03-17 10:43
The first issue is known and is a duplicate of https://github.com/2shady4u/godot-sqlite/issues/32
This will hopefully be fixed in the next update (whenever I have some free time 😱 )

Your side note is actually a lot more interesting as this is unexpected behaviour.... will test ASAP and get back to you

**Comment by 2shady4u** [comment] 2021-03-17 11:17
![image](https://user-images.githubusercontent.com/42484461/111458909-55019a80-871a-11eb-9b7e-bce1a6bd5cb8.png)

So I tested it somewhat and get the same error.
When not putting a "?" in for the data-column everything works perfectly.

I'll have to check, but I actually think you can't bind columns in this way.
So you'll have to change your query to this:
```gdscript
db.query_with_bindings("UPDATE users SET myblob=? WHERE uid = ?;", [PoolByteArray([1,2]), uid])
```

or if you still want the "myblob" value to be variable:
```gdscript
db.query_with_bindings("UPDATE users SET " + "myblob" +"=? WHERE uid = ?;", [PoolByteArray([1,2]), uid])
```

**Comment by 2shady4u** [comment] 2021-03-17 11:20
After a little bit of searching I found this:
http://sqlite.1065341.n5.nabble.com/Binding-a-column-name-td1045.html

So it's a SQLite restriction that applies here and not an issue of the plugin itself! 😅

**Comment by 2shady4u** [comment] 2021-03-18 22:42
Can I close this issue then? Since this is a duplicate from #32 and the secondary issue is due to an SQLite restriction and doesn't directly relate to the Godot-SQLite plugin itself?

**Comment by mrimvo** [comment] 2021-03-19 14:37
Yes you can close it, thank you :)

Maybe add a hint to the docu about the secondary issue, for the next person 
stumbling over it 👍

Am 18. März 2021 23:43:09 schrieb Piet Bronders ***@***.***>:

**Comment by 2shady4u** [comment] 2021-03-19 18:21
will do!

**Closed** 2021-03-19 21:09 UTC
