### ISSUE TITLE
Error message about trying to close a db that's not open

### ISSUE THREAD

**Issue by scotmcp** [2shady4u/godot-sqlite#169] opened 2024-02-27 03:41 UTC
**Environment:**
 - OS:  Linux Mint 21.3
 - Godot version:  v4.2.1.stable.mono.flathub [b09f793f5]
 - _godot-sqlite_ version:  4.3

**Issue description:**

On opening the sqlite database, getting error:
  GDSQLite Error: Can't close database if connection is not open!

I am pasting the entirety of my database class as it exists now. I have searched my entire project for errant db.close() statements, and there are none.

**Steps to reproduce:**
You have to run my project, which is far too big to paste here, however I did paste my database class in. I cannot find logic that would cause a db.close() to happen without an instance being opened first.

Additionally, it sometimes produces there error open the very first openning of the database (giving the message that it can't close the database that isn't open)

**Minimal reproduction project:**
[database.db.tar.gz](https://github.com/2shady4u/godot-sqlite/files/14413985/database.db.tar.gz)

**Additional context**
![image](https://github.com/2shady4u/godot-sqlite/assets/79280460/17537931-8f3a-406b-bf29-8935566f7f2f)

![image](https://github.com/2shady4u/godot-sqlite/assets/79280460/c0d0b252-c760-4d89-8a5b-60f8274db57f)

**Comment by 2shady4u** [comment] 2024-02-27 07:10
Hello! I will investigate as soon as possible.
There is a chance this might be caused by the `close_db()`-method call in the plugin's destructor.
In which case the issue is caused by me 🙈

**Comment by 2shady4u** [comment] 2024-02-27 19:06
@scotmcp I have pushed a small fix since that addresses the issue.
Updated binaries will be part of the next release, but you can already download the new binaries here:
https://github.com/2shady4u/godot-sqlite/actions/runs/8070008064

Could you confirm that the issue is fixed when you use the new binary? 😃

**Comment by scotmcp** [comment] 2024-02-27 19:13
I'll check it out later, looks like it's all still building.

**Comment by scotmcp** [comment] 2024-02-27 19:41
Well regardless of whether I know what I am talking about or not, the new libraries seem to work great for Linux....I haven't tested in Windows, but I assume it will work there too.

**Comment by scotmcp** [comment] 2024-02-27 21:01
I guess what I don't understand is...why fixing the destructor solves the problem of trying to close the database when what I am doing is opening the database, does the constructor look for an instance to destroy first, like a singleton?

**Comment by 2shady4u** [comment] 2024-02-28 06:52
> I guess what I don't understand is...why fixing the destructor solves the problem of trying to close the database when what I am doing is opening the database, does the constructor look for an instance to destroy first, like a singleton?

I am not 100% sure, but I think the editor instances the SQLite class to get access to its internal methods for documentation and autocompletion purposes. This instance then gets destroyed by the editor, resulting in the 'close_db()'-method call which results in the error you are experiencing.

**Comment by scotmcp** [comment] 2024-02-28 14:39
THAT makes sense :)

Thank you!!

**Closed** 2024-02-28 14:39 UTC
Labels: bug
