### ISSUE TITLE
Encryption and decryption

### ISSUE THREAD

**Issue by hidemat** [2shady4u/godot-sqlite#56] opened 2021-09-01 04:47 UTC
**Is your feature request related to a problem? Please describe.**

In order to protect sensitive information stored in the Database, encryption and decryption functionality would be nice.

**Describe the solution you'd like**

1.  Adding a function like `db.set_password(password -> string)` that would then encrypt the database using that passphrase.
2. Adding a property like `db.password` to provide the database object with the password do decrypt the file.

**Describe alternatives you've considered**

I've actually successfully encrypted a Sqlite db using C#, but the export features of Godot Mono aren't production ready and I've run into some game-breaking issues.

**Additional context**

**Comment by 2shady4u** [comment] 2021-09-01 08:54
@hidemat This is a duplicate of https://github.com/2shady4u/godot-sqlite/issues/23
As discussed in that issue, I was able to get MVP database encryption/decryption working using SQLeet.

I'll leave this one open for now 🤔 
At least until I have some more time to work/think about this 🙏

**Comment by hidemat** [comment] 2021-09-01 12:37
Oh my apologies a did a search with the word encrypt and didn't find it. My bad. Thanks, best of luck.

**Comment by 2shady4u** [comment] 2021-09-12 12:06
Closing this issue in favor of https://github.com/2shady4u/godot-sqlite/issues/23 as they are identical.
Please continue any discussion on this subject there.

**Closed by 2shady4u** 2021-09-12 12:06 UTC
Labels: enhancement
