### ISSUE TITLE
Html5 saving

### ISSUE THREAD

**Issue by fireworx** [2shady4u/godot-sqlite#112] opened 2022-12-05 12:30 UTC
closing of db doesn't save in indexdb,

but saving after closing db, a new dummy file will enforce that db is saved

maybe a chance for a generally workaround ;-)

**Comment by 2shady4u** [comment] 2022-12-05 17:38
Hey @fireworx!
Would it be possible to give the code to a minimal reproduction project such that I can better understand the issue?

The database should be automatically saved when you close it and should be stored in the user://-folder.

**Comment by fireworx** [comment] 2022-12-05 18:52
`
var table_name="terrain"

func g(debug:bool)->SQLite:
	var db = SQLite.new()
	db.path = db_name
#	db.default_extension=""
	if debug:
#		db.verbose_mode = true
		db.verbosity_level=3
	db.open_db()
	return db

func _init():
	db = DB.g(1)

	var table_dict : Dictionary = Dictionary()
	table_dict["id"] = {"data_type":"int", "primary_key": true, "not_null": true,"autoincrement":true}
	table_dict["name"] = {"data_type":"text", "not_null": true}
	table_dict["timestamp"] = {"data_type":"int", "not_null": true}
	table_dict["imageid"] = {"data_type":"int", "not_null": false}
	db.create_table(table_name, table_dict)
        db.close_db()


func addNewTerrain(instanceid):
	db = DB.g(1)

	var tname=instance_from_id(instanceid).text
	var format_string ="INSERT INTO %s (name,timestamp) VALUES ('%s', %d)"
	var whereclause = format_string % [table_name,tname,OS.get_unix_time()]
	var _qry = db.query(whereclause)
	db.close_db()
	$BTNnew.show()
	reloadTerrains()
`

**Comment by fireworx** [comment] 2022-12-05 19:02
the func g() is in a singleton for global usage within all scripts

**Comment by fireworx** [comment] 2022-12-06 08:51
[testsql.zip](https://github.com/2shady4u/godot-sqlite/files/10164388/testsql.zip)

**Comment by fireworx** [comment] 2022-12-06 08:53
try it with and without dummysave(), it will not write /userfs/test.db when changes are made

**Comment by 2shady4u** [comment] 2022-12-06 09:33
Hi @fireworx 

I currently don't have time to actually run that code.
One thing I've noticed is that you are dropping your table each time you restart/reload your application:

```gdscript
	# Throw away any table that was already present
	db.drop_table(table_name)
```

I'll try to run your code as soon as I can.

**Comment by 2shady4u** [comment] 2022-12-08 08:45
Hi @fireworx,

I finally had some time to try and replicate the issue.
As a result, I've successfully replicated the issue; there's indeed something strange going on with the database saving on HTML5.

I'll try to find some time as soon as possible to figure out what is going on and hopefully get it fixed.

**Comment by 2shady4u** [comment] 2022-12-26 13:50
It seems that Godot doesn't automatically sync the userfs in HTML.
The user filesystem only gets synced whenever the `close()`-method gets called on a `File`, as found here:
https://github.com/godotengine/godot/blob/4e48b855d5cd5dc21e0cabd659386c0d0f425acf/platform/javascript/os_javascript.cpp#L1034

Easiest work-around at the time of writing seems to be to simply open a dummy file as such:
```gdscript
var file := File.new()
file.open("user://whatever", File.WRITE)
file.close()
```

This will force Godot to sync the filesystem when this file closes.

**Comment by 2shady4u** [comment] 2022-12-26 13:58
A feasible fix might be to allow the user to select the VFS (default or the godot one); in which case the files sync automatically whenever you use the godot VFS.

**Comment by 2shady4u** [comment] 2022-12-27 08:21
I've ran into some issues as found here: https://github.com/godotengine/godot-cpp/issues/978

We'll see what comes out of it! 😄

**Comment by 2shady4u** [comment] 2022-12-27 11:56
I've ported the above code snippet and added it to the `close_db()`-method in the `fix-html-saving`-branch.
Unfortunately it seems that this is actually not supposed to work as the `GodotFS`-property should actually not be exposed.
The so-called [closure compiler](https://developers.google.com/closure/compiler) is supposed to rename/minimize this object in official builds, but, for some reason, it is not enabled in the latest Godot builds.

As a result, there's two options here:
- We create and delete a dummy file using the Godot's `File`-class such that the file system gets synced.
- We wait until https://github.com/godotengine/godot/pull/70626 gets backported to GDNative such that I can call the new `force_fs_sync()`-method to forcefully sync the file system whenever the database gets closed.

**Comment by 2shady4u** [comment] 2022-12-30 08:41
Hi @fireworx 

I've decided on an entirely different approach, namely to always use the custom VFS for HTML targets.
As the custom VFS shim uses Godot's File class internally, the file system will be synced automatically whenever the database gets closed as the internal file will also get closed.

A small concern is the matter of speed (SQLite's default VFS vs. my custom VFS), but I think the difference will be negligible.

**Comment by 2shady4u** [comment] 2022-12-31 13:48
Posting this here for future reference:

```C++
#ifdef __EMSCRIPTEN__
            /* In the case of the web build, we'll have to manually force an update of the file system (IndexedDB) */
            /* The method used here is dangerous as the GodotFS object *might* not be exposed on official builds due to the closure compiler renaming/minimizing the property */
            Ref<JavaScriptObject> engine = JavaScript::get_singleton()->get_interface("engine");
            Ref<JavaScriptObject> rtenv = engine->get("rtenv");
            Ref<JavaScriptObject> GodotFS = rtenv->get("GodotFS");
            if (!GodotFS->get("_syncing"))
            {
                GODOT_LOG(0, "Manually forcing GodotFS to sync!");
                GodotFS->call("sync");
            }
#endif
```

**Comment by 2shady4u** [comment] 2022-12-31 14:55
This issue has now been fixed in the latest release (https://github.com/2shady4u/godot-sqlite/releases/tag/v3.5) 🥳 

Thank you for reporting this issue and enjoy your coding!

**Closed by 2shady4u** 2022-12-31 14:55 UTC
Labels: bug
